# Generated by Django 6.0.6 on 2026-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma separated: Django, Python, React', max_length=300)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repo link')),
                ('live_url', models.URLField(blank=True, help_text='Live demo link (optional)')),
                ('accent_color', models.CharField(choices=[('cyan', 'Cyan (Purple)'), ('mint', 'Mint (Light Purple)'), ('rose', 'Rose (Dark Purple)'), ('blue', 'Blue')], default='cyan', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
