# Generated by Django 6.0.6 on 2026-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project screenshot or thumbnail', null=True, upload_to='projects/'),
        ),
    ]
